### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by xxopenxx** [AstraaDev/Discord-All-Tools-In-One#1]
I have an issue, i can't paste token into the console using some functions like token-information, when i paste it just blank text paste and says invalid token. I'm sure my tokens are workin beacuse i manually checked it

**Comment by xxopenxx** [comment]
But overally i love this tool. Converting rat to exe doesnt work for me too.

**Comment by AstraaDev** [comment]
Hey xxopenxx, I will take care to see where the problem could come from concerning your token. But the problem occur only with your token or with any token? 

Concerning the RAT conversation in Exe, I am currently working on a Patch.

**Comment by xxopenxx** [comment]
It's working perfect when i manually write a token into the console, but when i try to paste token it's pasting blank thing and says invalid token. Maybe that's a problem from my side, it'spretty possible. 

Can you add like token creator in future? It's not that easy but possible. 2captcha or maybe hcaptcha bypass and 5sms api for example

**Comment by AstraaDev** [comment]
I think it is indeed a problem related to your browser because I made several tests on different machines and I did not see this problem.

Concerning the token creator, why not ! That could be interesting to do.
