### ISSUE TITLE
[SUGGESTION] Dm for ads feature.

### ISSUE THREAD

**Issue by xxopenxx** [AstraaDev/Discord-All-Tools-In-One#11]
Is it possible to add feature that can scrape all members from guilds, than massdm everyone with custom ad?

**Comment by AstraaDev** [comment]
Humm yes it is possible, good idea! Maybe in the next update :)

**Comment by xxopenxx** [comment]
https://github.com/hoemotion/mass-dm-discord There is good example how it works!
