### ISSUE TITLE
Errors on the Token Grabber

### ISSUE THREAD

**Issue by ProxyC0ding** [AstraaDev/Discord-All-Tools-In-One#13]
File "C:\Users\#####\Desktop\Tools\AstraaTool\Additional_File\6_TokenGrab\tokengrabber.py", line 19, in tokengrabber
    print(f"""[{w}+]{w} Enter the name you want to give to the final file: """)
NameError: name 'w' is not defined

**Comment by AstraaDev** [comment]
Don't run the token grabber script directly but run the file "AstraaHome" and choose the option "Token Grabber". Normally you won't have any problem. :)
