### ISSUE TITLE
Virus ?

### ISSUE THREAD

**Issue by synczzzzzy** [AstraaDev/Discord-All-Tools-In-One#23]
hello i admire your knowledge of discord tools and i would like to know if this is safe and not a virus or a rat. please tell me if theres a video that i can watch to show its legit

**Comment by cliphd** [comment]
the code is literally given to you

**Comment by AstraaDev** [comment]
There was one but unfortunately it was deleted by Youtube a few months ago and I didn't have the time to make another one.
But the code is entirely given to you, so if you have any doubts, you just have to read it and you will see that it contains nothing malicious.
