### ISSUE TITLE
QR code grabber fails

### ISSUE THREAD

**Issue by nomrsavage** [AstraaDev/Discord-All-Tools-In-One#25]
this is all it gives...
a chrome window does open though
![image](https://user-images.githubusercontent.com/64970074/150231582-aadc90ef-d4a6-4773-bcac-9098ec6fc4bf.png)

**Comment by nomrsavage** [comment]
i just tried on my main ssd, and it doesnt work there either

**Comment by S1mp1yDucky** [comment]
same issue here

**Comment by nomrsavage** [comment]
Never mind, using python 3.9 instead of 3.10 solves stuff (as of now)
