### ISSUE TITLE
nitrogen not working

### ISSUE THREAD

**Issue by RealFrazix** [AstraaDev/Discord-All-Tools-In-One#60]
i open then it closes

**Comment by peepeeslayer46** [comment]
Should be fixed now but A LOT of them are going to be invalid

**Comment by AstraaDev** [comment]
The nitro gen works but it is still BrutForce. There is very little chance that it will work.

**Comment by CrypticRalseiii** [comment]
Astraa how many attempts do you think is will take?

**Comment by Crackerinho** [comment]
> Astraa how many attempts do you think is will take?

This is luck based. For example if you gift a nitro and that nitro link is the same as the generated link you will get the nitro, so this is basically near impossible to get (only if you run it on multiple instances and 24/7 and hope someone doesnt get it before you do)

**Comment by CrypticRalseiii** [comment]
@Crackerinho thank you for telling me, only just revisited months later :P
