### ISSUE TITLE
Autologin with token not working

### ISSUE THREAD

**Issue by AltonSmasher** [AstraaDev/Discord-All-Tools-In-One#64]
When I autologin with my token it says there is a problem with your token and closes the chrome browser instantly

**Comment by carnageee** [comment]
same brethren

**Comment by MrShadowDev** [comment]
Same pls fix

**Comment by jven123** [comment]
the code outdated maybe

**Comment by MrShadowDev** [comment]
ye

**Comment by AstraaDev** [comment]
Do you have an error? Or does the browser just not open?

**Comment by jven123** [comment]
It also happens to me too

**Comment by DXVVAY** [comment]
This tool is outdated and doesnt work use my tool instead [xvirus-tools](https://github.com/Xvirus0/xvirus-tools)

**Comment by findmejojo** [comment]
@AstraaDev auto login token just says problem with token please fix

**Comment by AstraaDev** [comment]
Problem fixed.
