### ISSUE TITLE
Qr Code Webhook error

### ISSUE THREAD

**Issue by MelloYourFello** [AstraaDev/Discord-All-Tools-In-One#68]
```<string>:43: DeprecationWarning: executable_path has been deprecated, please pass in a Service object```
i keep getting this error everytime i input my webhook.

**Comment by Crackerinho** [comment]
You can fix this by:
Going into the Util Folder
You can find the chromedriver (make sure to download the latest chromedriver [here](https://chromedriver.storage.googleapis.com/index.html?path=104.0.5112.79/))
And also don't forget to install Google Chrome

**Comment by Crackerinho** [comment]
And make sure to replace the chromedriver in the Util folder

**Comment by Crackerinho** [comment]
It also shows you some errors but just go on the output folder and ur good to go
If anything doesnt work just tell me i might be able to fix the issue

**Comment by MelloYourFello** [comment]
alright, i didn't have chrome installed (i use brave) so i installed chrome, but now it comes up with this (installed chromedriver as well)
```[!] Error: session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 104.0.5112.102 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe```

**Comment by MelloYourFello** [comment]
it works! ty!
