### ISSUE TITLE
dont download!

### ISSUE THREAD

**Issue by antoniosgithub** [AstraaDev/Discord-All-Tools-In-One#78]
![image](https://user-images.githubusercontent.com/114849567/198873152-3bedeca6-c3f1-4870-9dda-bf9fd8590879.png)

**Comment by pythondemon** [comment]
xd

**Comment by Solidbeast42** [comment]
broski are you stupid?

**Comment by MrShadowDev** [comment]
Its not a virus man!

**Comment by jven123** [comment]
lol xd its open source bro

**Comment by jven123** [comment]
> broski are you stupid?

His retarded

**Comment by MrShadowDev** [comment]
Ye, his so retard

**Comment by antoniosgithub** [comment]
mate i was trolling xD

Il giorno lun 26 dic 2022 alle ore 03:17 MrShadowDev <
***@***.***> ha scritto:

**Comment by jven123** [comment]
lol
