### ISSUE TITLE
bro the text are crazy can someone help?

### ISSUE THREAD

**Issue by SneakNPeak** [AstraaDev/Discord-All-Tools-In-One#83]
![image](https://user-images.githubusercontent.com/88135234/208264541-643e5d4f-d739-4868-8931-d0be5de7a436.png)

**Comment by Domman19** [comment]
sometimes it happens with python

**Comment by Domman19** [comment]
its like colorama

**Comment by Domman19** [comment]
but it glitches out because colorama prints a string that looks like [00m and that changes the colour, sometimes python glitches out and just prints the raw string

**Comment by jven123** [comment]
wht os is ur computer?

**Comment by jven123** [comment]
it works in windows 10+

**Comment by AstraaDev** [comment]
Being on Windows everything should work fine.
