### ISSUE TITLE
Converting scripts to exes doesn't work.

### ISSUE THREAD

**Issue by SneeezEX** [AstraaDev/Discord-All-Tools-In-One#92]
Tried it twice on 06 (File Grabber). Made the script but didn't convert despite confirming success.

**Comment by AstraaDev** [comment]
Do you have a display error? What's wrong?

**Comment by SneeezEX** [comment]
No, don't see how this could be affected by the display, but it just doesn't convert the .py file into an executable.
![image](https://user-images.githubusercontent.com/97247795/221570832-5907a883-d164-4059-90ee-7b66f825b0cb.png)

**Comment by AstraaDev** [comment]
Everything works on my end. Your anti-virus must surely detect it and remove it instantly.
Disable it and try again.

**Comment by SneeezEX** [comment]
Sadly disabling my Antivirus didn't help. Maybe it's something on my end that I missed. As a final question, should the .exe file be created in the \output folder? I suppose so, but just in case I'm just looking in the wrong place.

**Comment by AstraaDev** [comment]
Yes, once the .exe file is created, you will find it in the `output` folder.
Do you have the python module `pyinstaller` on your PC? Do `pip install pyinstaller`. What version of Python are you using? You need Python 3.9.

**Comment by SneeezEX** [comment]
That could be the issue, because I have python 3.10 installed. I actually already converted the files with auto-py-to-exe, so I can do it manually. I don't really want to switch to python 3.9, but still, thanks for helping me in this rather long conversation :)
